
platform :ios, '15.0'

def shared_pods
  use_frameworks!
  pod 'SnapKit'
  pod 'StandardCyborgFusion', '2.3.2'
end

target 'FootScannApp' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end

